# Generated by Django 3.1.7 on 2021-04-18 15:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderPlaced',
            new_name='PlacedOrder',
        ),
    ]
