# Generated by Django 3.1.7 on 2021-04-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210418_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('MTW', 'Men Top Wear'), ('FTW', 'Female Top Wear'), ('MBW', 'Men Bottom Wear'), ('FBW', 'Female Bottom Wear'), ('M', 'Mobile'), ('L', 'Laptop')], max_length=100),
        ),
    ]
